# Generated by Django 3.2.13 on 2023-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_alter_partie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='numquestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partie',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
