# Generated by Django 3.2.13 on 2023-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20230305_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='numquestion',
            field=models.IntegerField(default=1),
        ),
    ]
